name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o linux_sophos_cli

      - name: Build for macOS
        run: GOOS=darwin go build -o macos_sophos_cli

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o win_sophos_cli.exe
      
      - name: Get version number
        id: version
        run: |
          echo "::set-output name=version::$(date +%Y%m%d%H%M%S)"
          
      - name: Get commit information
        run: |
          COMMIT_MESSAGE="$(git log -1 --pretty=format:'%s')"
          COMMITS_SINCE_TAG="$(git rev-list --count $(git describe --tags --abbrev=0 HEAD)..HEAD)"
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "COMMITS_SINCE_TAG=$COMMITS_SINCE_TAG" >> $GITHUB_ENV
          
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          body: |
            This is release v${{ steps.version.outputs.version }} 
          draft: false
          prerelease: false

      - name: Upload Linux binary
        uses: actions/upload-artifact@v2
        with:
          name: sophos_cli
          path: ./linux_sophos_cli

      - name: Upload macOS binary
        uses: actions/upload-artifact@v2
        with:
          name: sophos_cli
          path: ./macos_sophos_cli

      - name: Upload Windows binary
        uses: actions/upload-artifact@v2
        with:
          name: sophos_cli
          path: ./win_sophos_cli.exe

      - name: Attach Linux binary to release
        id: attach_linux_binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux_sophos_cli
          asset_name: sophos_cli
          asset_content_type: application/octet-stream

      - name: Attach macOS binary to release
        id: attach_macos_binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos_sophos_cli
          asset_name: sophos_cli
          asset_content_type: application/octet-stream

      - name: Attach Windows binary to release
        id: attach_windows_binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./win_sophos_cli.exe
          asset_name: sophos_cli.exe
          asset_content_type: application/octet-stream
